---
name: SimpleFeed
api: 4.0.0
version: 2.0.0
main: Electro\SimpleFeed\Main
author: Electro
description: Feed yourslef or others to max food

commands:
 feed:
  description: Feed yourslef or others to max food
  permission: simplefeed.use
permissions:
  simplefeed.use:
    description: Permission to feed yourself or others
    default: op
...

